labels:
  - { name: area/standards, color: 0366d6, description: Standards mapping & clauses }
  - { name: area/comparison, color: 0e8a16, description: Cross-jurisdiction comparisons }
  - { name: area/extractor, color: 1d76db, description: Crawlers & ingestion }
  - { name: status/Backlog, color: cccccc }
  - { name: status/Todo,    color: 5319e7 }
  - { name: status/Doing,   color: 1d76db }
  - { name: status/Review,  color: fbca04 }
  - { name: status/Blocked, color: b60205 }
  - { name: status/Done,    color: 0e8a16 }
  - { name: priority/P0, color: b60205 }
  - { name: priority/P1, color: d93f0b }
  - { name: priority/P2, color: fbca04 }
  - { name: priority/P3, color: cccccc }
  - { name: milestone/phase-0, color: bfd4f2, description: Phase 0 – Baseline }
  - { name: milestone/phase-1, color: bfd4f2, description: Phase 1 – Corpus & Standards }
  - { name: milestone/phase-2, color: bfd4f2, description: Phase 2 – Comparison Engine }
  - { name: milestone/phase-3, color: bfd4f2, description: Phase 3 – Annotations & Issues }
  - { name: milestone/phase-4, color: bfd4f2, description: Phase 4 – Guidance UI }
