name: Auto milestone from labels
on:
  issues:
    types: [opened, edited, labeled, unlabeled, reopened]
  pull_request:
    types: [opened, edited, labeled, unlabeled, reopened, ready_for_review]
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const item = context.payload.issue || context.payload.pull_request;
            const labels = (item.labels || []).map(l => typeof l === 'string' ? l : l.name);
            const map = {
              'milestone/phase-0': 'Phase 0 – Baseline',
              'milestone/phase-1': 'Phase 1 – Corpus & Standards',
              'milestone/phase-2': 'Phase 2 – Comparison Engine',
              'milestone/phase-3': 'Phase 3 – Annotations & Issues',
              'milestone/phase-4': 'Phase 4 – Guidance UI',
            };
            const key = labels.find(n => (n||'').toLowerCase().startsWith('milestone/'));
            if (!key) return;
            const owner = context.repo.owner, repo = context.repo.repo;
            const {data: ms} = await github.rest.issues.listMilestones({owner, repo, state:'all'});
            const m = ms.find(x => x.title === map[key]);
            if (m) await github.rest.issues.update({owner, repo, issue_number: item.number, milestone: m.number});
