
    name: CI
    on:
      push:
      pull_request:
      workflow_dispatch:
    jobs:
      verify:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Python checks (noop)
            run: |
              python -V
              echo "CI sanity OK"
