
    name: Release Drafter
    on:
      push:
        branches: [ master ]
      pull_request:
        types: [closed]
      workflow_dispatch:
    jobs:
      update_release_draft:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 1
          - name: Determine default branch
            id: def
            run: |
              branch=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
              echo "branch=${branch:-master}" >> $GITHUB_OUTPUT
          - name: Fetch default branch
            run: |
              git fetch --no-tags --depth=1 origin "${{ steps.def.outputs.branch }}":refs/remotes/origin/"${{ steps.def.outputs.branch }}"
          - name: Check release-drafter config on default branch
            id: check
            run: |
              if git show "origin/${{ steps.def.outputs.branch }}:.github/release-drafter.yml" >/dev/null 2>&1; then
                echo "skip=false" >> $GITHUB_OUTPUT
              else
                echo "Config not on default branch (${{ steps.def.outputs.branch }}); skipping."
                echo "skip=true" >> $GITHUB_OUTPUT
              fi
          - uses: release-drafter/release-drafter@v5
            if: steps.check.outputs.skip != 'true'
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              config-name: release-drafter.yml
