
    name: Release Drafter
    on:
      push:
        branches: [ master ]
      pull_request:
        types: [closed]
      workflow_dispatch:
    jobs:
      update_release_draft:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: release-drafter/release-drafter@v5
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              config-name: release-drafter.yml
