
    name: Semantic Pull Request
    on:
      pull_request:
        types: [opened, edited, synchronize]
      workflow_dispatch:
    jobs:
      semantic:
        permissions:
          pull-requests: read
        runs-on: ubuntu-latest
        steps:
          - uses: amannn/action-semantic-pull-request@v5
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              types: |
                chore,ci,docs,feat,fix,perf,refactor,revert,style,test,build
